/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AntDesignLikeOutlined: typeof import('~icons/ant-design/like-outlined')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    FluentDividerShort20Filled: typeof import('~icons/fluent/divider-short20-filled')['default']
    Footer: typeof import('./src/components/layout/footer/index.vue')['default']
    GlobalImage: typeof import('./src/components/globalImage/index.vue')['default']
    GravityUiServer: typeof import('~icons/gravity-ui/server')['default']
    Header: typeof import('./src/components/layout/header/index.vue')['default']
    IcOutlineRemoveRedEye: typeof import('~icons/ic/outline-remove-red-eye')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    Main: typeof import('./src/components/layout/main/index.vue')['default']
    MaterialSymbolsDateRange: typeof import('~icons/material-symbols/date-range')['default']
    MaterialSymbolsMarkChatUnreadOutline: typeof import('~icons/material-symbols/mark-chat-unread-outline')['default']
    MdiAbjadHebrew: typeof import('~icons/mdi/abjad-hebrew')['default']
    MdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    PageHeader: typeof import('./src/components/page-header/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SolarCardSendLinear: typeof import('~icons/solar/card-send-linear')['default']
    Store: typeof import('./src/store/index.js')['default']
    SvgIcon: typeof import('./src/components/svg-icon/index.vue')['default']
    TablerClockHour2: typeof import('~icons/tabler/clock-hour2')['default']
  }
}
